### PR TITLE
[new] wholesome 404 template

### PR DESCRIPTION
**Pull request by realanupreet**
image
Hope it adds value!

### CODE REVIEW

**Comment by realanupreet** [comment]
hey @matteobruni , could you please review this pr?
please let me know if there's anything wrong with it?

**Comment by realanupreet** [comment]
hey @matteobruni please review this pr, because after that only i would be able to fix the #74 otherwise my every commit will come to this pr only which might not be clean

**Review by matteobruni — DISMISSED** [review]
There's a conflict, but the template is fine. Please solve the conflict and this will be merged

**Comment by realanupreet** [comment]
have resolved the conflicts

**Pull request merged**
