### PR TITLE
Tidy up JS file

### PR DESCRIPTION
**Pull request by nataliedeweerd**
Combined addClass functions to make the code neater.

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
Ok about using a single `addClass` call, but please restore the new lines between the variable declarations and their usages.

**Comment by nataliedeweerd** [comment]
> Ok about using a single `addClass` call, but please restore the new lines between the variable declarations and their usages.

Done! :)

**Review by matteobruni — CHANGES_REQUESTED** [review]
Please merge this PR and #30

**Review by matteobruni — CHANGES_REQUESTED** [review]
I don't see the merge between this PR and #30. I won't accept two PR for two files in the same page.

**Pull request closed without merging**
