### PR TITLE
Adding dark-mode CSS to index

### PR DESCRIPTION
**Pull request by nataliedeweerd**
Plus minor formatting tweaks.

screenshot-127 0 0 1_8080-2022 10 02-23_49_19

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
I don't see the merge between this PR and #28. I won't accept two PR for two files in the same page.

**Comment by nataliedeweerd** [comment]
@matteobruni They're two separate improvements, modifying 2 independent files. Why do you want them merged to a single PR?

**Comment by matteobruni** [comment]
> @matteobruni They're two separate improvements, modifying 2 independent files. Why do you want them merged to a single PR?

They are both for improving the index page, it's not the best practice to open a PR for every single file edited.

**Comment by nataliedeweerd** [comment]
@matteobruni Oh I agree! But since they're separate improvements (for me) it makes sense to keep them separate. However I shall merge them for you now.

**Pull request closed without merging**
