### PR TITLE
Add ocean template

### PR DESCRIPTION
**Pull request by yanina-nas**
Added an ocean themed 404 template for the issue https://github.com/tsparticles/404-templates/issues/18 using tsparticles.

ocean

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
Particles are barely visible, I'd like something that uses particles for creating a cool main animation instead of something that is almost unnoticeable.

**Comment by yanina-nas** [comment]
@matteobruni My bad :) I reworked it a bit, made particles more noticeable. Please check again

**Comment by yanina-nas** [comment]
New look:
ocean

**Review by matteobruni — APPROVED** [review]
Looks good now, thanks

**Pull request merged**
