### PR TITLE
#18 Add new 404 template

### PR DESCRIPTION
**Pull request by tannudaral**
Added autumn theme

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
Can you make particles more visible? I think the opacity is too low.

You can set a wider range for the opacity, or the bubble effect can set a different opacity too

**Comment by tannudaral** [comment]
Hey! Does this look good?
image

**Comment by tannudaral** [comment]
Pls check now!

**Review by matteobruni — APPROVED** [review]
Looks good now, good job

**Pull request merged**
