### PR TITLE
added new template for 404 using tsparticle.js with dark and light theme using toggle action by user

### PR DESCRIPTION
**Pull request by Khushalsarode**

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
Please create a single theme since they're the same except for the background. Use media queries and/or a button for switching themes.
Please also split CSS and JS to their own files instead of having a single html file.
Please give a better name than 404 or t404.

**Review by matteobruni — CHANGES_REQUESTED** [review]
I didn't notice in previous files, but I notice it now. You are using particles.js in this template and not tsParticles. Using tsParticles is *mandatory*.
Please call the html file 404.html.
Read carefully #97, there are missing requirements

**Comment by Khushalsarode** [comment]
hey! @matteobruni I updated code using tsparticles!
please check the needed, and let me know if something required.
screenshots!
Screenshot 2023-10-26 195503
Screenshot 2023-10-26 195531

**Review by matteobruni — CHANGES_REQUESTED** [review]
Please read #97 instructions, there are still missing things from there, and use the `tsparticles@2` handle, not a specific `1.9.2` version.

**Comment by Khushalsarode** [comment]
> Please read #97 instructions, there are still missing things from there, and use the `tsparticles@2` handle, not a specific `1.9.2` version.

done!

**Review by matteobruni — CHANGES_REQUESTED** [review]
The checks are failing, I can't approve it until they pass

**Pull request closed without merging**
