### PR TITLE
Adding new 404 error themes 

### LINKED ISSUE #155: Feature Request: Want to add two new theme: "galaxy" & "starwars"
### Contact Details

khushalsarode.in@gmail.com

### What is your request?

- have created an two new 404 theme using tsparticles
- galaxy: galaxy related theme with asteroid and space void saying you are lost!
- starwars: 404 wars! force leaved you! 
galaxy
starwars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Khushalsarode**
1. galaxy
2. starwars

screenshot:
galaxy
starwars

closes #155 

## Summary by CodeRabbit

- **New Features**
	- Introduced new custom 404 error pages for "Galaxy" and "Star Wars" themes to enhance user experience.
	- Implemented engaging designs and animations for the 404 error pages.

- **Styling**
	- Added unique CSS styles for "Galaxy" and "Star Wars" themes to enrich the visual presentation of error pages.

- **Interactivity**
	- Implemented dynamic particle animations on error pages to create an immersive user experience.

### CODE REVIEW

**Comment by Khushalsarode** [comment]
@matteobruni 
should i only push the code, its failed as i edited and pushed data.json

**Comment by matteobruni** [comment]
> @matteobruni should i only push the code, its failed as i edited and pushed data.json

Don't worry about Codacy, only Node.js CI is required, and it's failing too.

**Comment by Khushalsarode** [comment]
@matteobruni can we try now?

**Comment by Khushalsarode** [comment]
Screenshot 2024-10-22 022106

@matteobruni

**Comment by Ebrahim136767** [comment]
> Screenshot 2024-10-22 022106
> 
> @matteobruni done

/

**Pull request merged**
