### PR TITLE
Added desert template

### PR DESCRIPTION
**Pull request by Ahsan-Ehtesham**
Added #18 
Added updated Desert template, kindly review @matteobruni

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
I don't know why another PR, but the issue is still there.

**Review by matteobruni — APPROVED** [review]
Now it's good, thanks

**Comment by Ahsan-Ehtesham** [comment]
> Now it's good, thanks

, at the end of pages.json was the main problem after all

**Comment by Ahsan-Ehtesham** [comment]
> Now it's good, thanks

Kindly add hacktoberfest-accepted label to this PR

**Comment by matteobruni** [comment]
It's not necessary, the repository is already tagged for hacktoberfest

**Pull request merged**
