### PR TITLE
Enhanced styling 

### PR DESCRIPTION
**Pull request by YashBawa**
The background styling of the home page of the website has been enhanced to make it look more vibrant . 
here is the demo of the changes :-
image

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
Please keep the original formatting. I can see a lot of lines changed only with spaces added or moved.

Also, I'm not convinced by the result, do you have other color ideas or improvements?

**Comment by YashBawa** [comment]
I added some div tags while formating them it got changed by prettier library. No issues it will be set to original. 
Yes ,I can present some better color suggestions.

**Comment by YashBawa** [comment]
hey @matteobruni , 
added a new background styling 
image
please review and verify it.

**Comment by matteobruni** [comment]
> hey @matteobruni ,
> added a new background styling
> image
> please review and verify it.

This doesn't look professional, sorry but I'd like something more modern

**Comment by YashBawa** [comment]
ok @matteobruni you should assign this issue to someone else for better results. Can I create another issue of adding a preloader to the Website and start working on it?

**Comment by matteobruni** [comment]
> ok @matteobruni you should assign this issue to someone else for better results. Can I create another issue of adding a preloader to the Website and start working on it?

I'm not in a hurry, you can use this opportunity to improve your web design skills. A preloader could be a good idea though.

**Comment by YashBawa** [comment]
Ok thanks a lot @matteobruni for another chance . It would be much helpful if you could share a ss or template for the same of what's the expectation for its design.

Preloader will be added , after I complete this👍np
Thank you !!

**Comment by matteobruni** [comment]
> Ok thanks a lot @matteobruni for another chance . It would be much helpful if you could share a ss or template for the same of what's the expectation for its design.
> 
> Preloader will be added , after I complete this👍np Thank you !!

I don't have any idea in particular. I've seen these templates and they look good: https://colorlib.com/wp/cat/portfolio/ or https://cssninja.io/category/all

You can see if you find some good colors or new ideas to improve the website in general.

**Comment by YashBawa** [comment]
ok, @matteobruni will try something like it.

**Pull request closed without merging**
