### PR TITLE
sumit added styling

### PR DESCRIPTION
**Pull request by sumitbaroniya**
img1
img2

### CODE REVIEW

**Comment by sumitbaroniya** [comment]
some of the screenshots are there

**Review by matteobruni — CHANGES_REQUESTED** [review]
You edited the index.html, which is loaded using AJAX, adding static content. Please revert that.

I don't like the new cards full width style, I prefer keeping the actual spacing.

**Comment by sumitbaroniya** [comment]
hovering effect of the cards added

**Review by matteobruni — CHANGES_REQUESTED** [review]
Can you please use a `body` selector in the CSS and change the `background-color` there? Revert the `index.html` since it can be left unchanged.

**Comment by sumitbaroniya** [comment]
Screenshot (6921)
Screenshot (6922)

**Comment by matteobruni** [comment]
Almost forgot, the PR #40 introduced the dark theme when the system is using a dark mode. Check that is compatible with that.

**Pull request closed without merging**
