### PR TITLE
add NeoSolarized Theme inspired 404;

### PR DESCRIPTION
**Pull request by ATH42**

### CODE REVIEW

**Review by matteobruni — CHANGES_REQUESTED** [review]
The `pages.json` file is not updated, please read here all the steps to follow: https://github.com/tsparticles/404-templates/issues/18

**Comment by ATH42** [comment]
sorry for the extra commit, forgot too sync.

and thanks for the quick review :)

**Review by matteobruni — CHANGES_REQUESTED** [review]
Please fix the empty space at the top

**Comment by matteobruni** [comment]
Screenshot 2022-10-02 alle 23 47 50

I'm talking about this space, it cuts particles for no reason. Please fix the HTML and the screenshot

**Review by matteobruni — COMMENTED** [review]
Looks good now

**Review by matteobruni — APPROVED** [review]

**Pull request merged**
