### PR TITLE
[FEAT] nord 404 page

### PR DESCRIPTION
**Pull request by ch3ber**
PR for hacktober fest.

Based in [nord theme](https://www.nordtheme.com/)

### CODE REVIEW

**Comment by ch3ber** [comment]
Fast preview 
image

**Comment by ch3ber** [comment]
New preview
image

**Comment by ch3ber** [comment]
Mobile preview
image

**Comment by ch3ber** [comment]
It is a pleasure to contribute to your project, I await the response to this PR :)

**Comment by ch3ber** [comment]
@matteobruni Can you add the hacktoberfest tag to this topic and assign this topic to me?
It is for [Hacktoberfest  requirements](https://hacktoberfest.com/participation/#maintainers).

**Review by matteobruni — CHANGES_REQUESTED** [review]
Please put particles on top of the background pattern.

**Comment by ch3ber** [comment]
I was trying but I couldn't move the CSS pattern, so I decided to remove it

image

**Review by matteobruni — APPROVED** [review]
Looks good to me

**Pull request merged**
